LIBPATH = ../../../lib
SYSPATH = ../../../sys
WEBXRPATH = ../../../webxr

run:
	docker run -it --rm -v $(PWD):/workspace alma-emcc:latest

mr:
	emcc -O2 \
		-s EXPORTED_FUNCTIONS=_invokeFunctionsCallback,_updateModeCallback \
		-s ERROR_ON_UNDEFINED_SYMBOLS=0 \
		-o out.js \
		-I. \
		-I $(LIBPATH) \
		-I $(SYSPATH) \
		-I $(WEBXRPATH) \
		-D ARCS_MR \
		*.cc $(WEBXRPATH)/WebXR.cc \
		$(SYSPATH)/ARCSgraphics.cc \
		$(SYSPATH)/ARCSscrparams.cc \
		2>&1 \
	| grep -v -e "warning: undefined symbol: canGetWriteVariable" \
		-e "warning: undefined symbol: getWriteVariable" \
		-e "warning: undefined symbol: setActuatorStatus" \
		-e "warning: undefined symbol: canGetWriteVariable" \
		-e "warning: undefined symbol: setAxisRadian" \
		-e "warning: undefined symbol: setPlot" \
		-e "warning: undefined symbol: setReadVariable" \
		-e "warning: undefined symbol: setWriteVariable" \
		-e "emcc: warning: warnings in JS library compilation" \
		|| true

start:
	$(eval DIGEST := $(shell shasum -ba 256 out.wasm | cut -d ' ' -f1))
	$(eval DEST := gs://scrap-gcc-emcc/$(DIGEST).bin)
	$(eval URL := https://storage.googleapis.com/scrap-gcc-emcc/$(DIGEST).bin)
	$(eval ARTIFACT := $(shell printf "%s" "$(URL)" | base64 | tr '+/' '-_' | tr -d '='))

	gsutil cp out.wasm $(DEST)
	open "https://robot-arm-vr.vercel.app/?artifact=$(ARTIFACT)"
